name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 2
      - run: git checkout HEAD^
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git status
          git add .
          git commit -m "generated"
          git push origin $GITHUB_HEAD_REF
